# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Prismium

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

concurrency:
  group: prismium-release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          config: .goreleaser-prismium.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
